package tests

var Port = 7540
var DBFile = "../scheduler.db"
var FullNextDate = true
var Search = true
var Token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoZW50aWNhdGVkIjp0cnVlLCJleHAiOjE3NjUwNjQ3NjUsImlzcyI6ImdvLXRhc2stbWFuYWdlci1maW5hbF9wcm9qZWN0IiwicGFzc3dvcmRfaGFzaCI6IjU5OTQ0NzFhYmIwMTExMmFmY2MxODE1OWY2Y2M3NGI0ZjUxMWI5OTgwNmRhNTliM2NhZjVhOWMxNzNjYWNmYzUifQ.RAXj-2wHzxlkt2qEKcgG9IZGUIr17dZp0kHcbpvEy4k`
