package tests

var Port = 7540
var DBFile = "../scheduler.db"
var FullNextDate = true
var Search = true
var Token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoZW50aWNhdGVkIjp0cnVlLCJleHAiOjE3NjM5NjI0MDksImlzcyI6ImdvLXRhc2stbWFuYWdlci1maW5hbF9wcm9qZWN0IiwicGFzc3dvcmRfaGFzaCI6IjIyMjQ1MTJlZjQ0YTYyZTU4MGJiMWMwZGNiMzNhZmY2ODhmNGU3ZGE4YTQ4OGFlYjRlN2NhNDAyYzVjYWNmNDUifQ.zvZQU_Oj8GOzDfGu0425uu8zIJq1RaNkLD9omM-OmZg`
